In [1]:
import pandas as pd
import numpy as np
import pymongo
import os
from dotenv import load_dotenv
import datetime as dt

data = pd.read_csv('./database/healthcare_dataset.csv')

In [2]:
def verify_data(data):
    print("Aperçu des données :")
    print(data.head())
    print("\nInformations sur les données :")
    print(data.info())
    print("\nStatistiques descriptives :")
    print(data.describe())

In [3]:
def clean_data(file_path):
    data = pd.read_csv('./database/healthcare_dataset.csv')
    # Ajout d'un index unique pour chaque patient
    data['patient_id'] = data.index
    # Supprimer les doublons et les valeurs manquantes
    data = data.drop_duplicates()
    data = data.dropna()
    # Renommer les colonnes pour plus de clarté
    data = data.rename(columns={"patient_id":"patient_id","Name":"name","Age":"age","Gender":"gender","Blood Type":"blood_type",
            "Medical Condition":"medical_condition","Date of Admission":"date_of_admission","Doctor":"doctor","Hospital":"hospital","Insurance Provider":"insurance_provider",
            "Billing Amount":"billing_amount","Room Number":"room_number","Admission Type":"admission_type","Discharge Date":"discharge_date","Medication":"medication","Test Results":"test_results"})
    # Normaliser les noms et arrondir les montants
    data['name'] = data['name'].str.title()
    data['name'] = data['name'].str.strip()
    data['billing_amount'] = data['billing_amount'].round(2)
    # Normaliser les dates
    data['date_of_admission'] = pd.to_datetime(data['date_of_admission'], unit='ms')
    data['discharge_date'] = pd.to_datetime(data['discharge_date'], unit='ms')
    return data

In [4]:
cleaned_data = clean_data(data)

In [38]:
ordre =["patient_id",
            "name",
            "age",
            "gender",
            "blood_type",
            "medical_condition",
            "date_of_admission",
            "doctor",
            "hospital",
            "insurance_provider",
            "billing_amount",
            "room_number",
            "admission_type",
            "discharge_date",
            "medication",
            "test_results"]
cleaned_data = cleaned_data[ordre]

In [45]:
cleaned_data.dtypes

name                             str
age                            int64
gender                           str
blood_type                       str
medical_condition                str
date_of_admission     datetime64[us]
doctor                           str
hospital                         str
insurance_provider               str
billing_amount               float64
room_number                    int64
admission_type                   str
discharge_date        datetime64[us]
medication                       str
test_results                     str
patient_id                     int64
dtype: object

In [36]:
cleaned_data.head()

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,patient_id
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328,Urgent,2024-02-02,Paracetamol,Normal,0
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,1
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,205,Emergency,2022-10-07,Aspirin,Normal,2
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78,450,Elective,2020-12-18,Ibuprofen,Abnormal,3
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,458,Urgent,2022-10-09,Penicillin,Abnormal,4

In [ ]:
load_dotenv()
file_path = os.environ.get("OUTPUT_DATA_PATH")
db_name = os.environ.get("MONGO_INITDB_DATABASE")
collection_name = os.environ.get("COLLECTION")
user = os.environ.get("MONGO_APP_USERNAME")
password = os.environ.get("MONGO_APP_PASSWORD")
mongodb_uri = os.environ.get("MONGO_URI", f"mongodb://{user}:{password}@localhost:27017/{db_name}")

In [23]:
mongodb_uri

'mongodb://root:root@localhost:27017/DataSoluTech'

In [ ]:

def import_to_mongodb(data,mongodb_uri):
    client = pymongo.MongoClient(mongodb_uri)
    db = client['DataSoluTech']
    chunk_size = 1000
    num_chunks = math.ceil((len(df) / chunk_size))
    chunks = []
        
    for i in range(num_chunks):
        start = chunk_size * i
        stop = start + chunk_size
        chunks.append(cleaned_data[start:stop])
    # itérer sur les blocs    
    for i in range(num_chunks):
        db.healthcare.insert_many(chunks[i].to_dict('records'))
        print(f"Chunk {i+1}/{num_chunks} imported successfully.")

In [ ]:
cleaned_data

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

In [ ]:
db_schema = {
    'Name': {
        'type': 'string',
        'minlength': 1,
        'required': True,
    },
    'Age': {
        'type': 'int',
        'minlength': 1,
        'required': True,
    },
    'Gender': {
        'type': 'string',
        "required": False,
        'enum': ['Male', 'Female', 'Other']
    },
    'Blood Type': {
        'type': 'string',
        'required': True,
        'enum': ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']
    },
    'Medical Condition': {
        'type': 'string',
        'required': True,
    },
    'Date of Admission': {
        'type': 'date',
        'required': True,
    },
    'Doctor': {
        'type': 'string',
        'required': True,
    },
    "Hospital": {
        "type": "string",
        "required": True
    },
    'Insurance Provider': {
        'type': 'string',
        'required': True,
    },
    'Billing Amount': {
        'type': 'float',
        'required': True,
    },
    'Billing Amount': {
        'type': 'float',
        'required': True,
    },
    'Billing Amount': {
        'type': 'float',
        'required': True,
    },
    'Room Number': {
        'type': 'int',
        'required': True,
    },
    'Admission Type': {
        'type': 'string',
        'required': True,
        'enum': ['Emergency', 'Elective', 'Urgent']
    },
    'Discharge Date': {
        'type': 'date',
        'required': True,
    },
    'Medication': {
        'type': 'string',
        'required': True,
    },
     'Test Results': {
        'type': 'string',
        'required': True,
        'enum' : ['Normal', 'Abnormal', 'Inconclusive']
    },
}

In [10]:
data.dtypes

name                      str
age                     int64
gender                    str
blood_type                str
medical_condition         str
date_of_admission         str
doctor                    str
hospital                  str
insurance_provider        str
billing_amount        float64
room_number             int64
admission_type            str
discharge_date            str
medication                str
test_results              str
dtype: object

In [9]:
import pandas as pd
import os
from dotenv import load_dotenv
from datetime import datetime as dt
# Fonction pour nettoyer les données
def clean_data(file_path):
    data = pd.read_csv(file_path)
    # Supprimer les doublons et les valeurs manquantes
    data = data.drop_duplicates()
    # Ajout d'un index unique pour chaque patient
    data['patient_id'] = data.index
    # Renommer les colonnes pour plus de clarté
    data = data.rename(columns={"patient_id":"patient_id","Name":"name","Age":"age","Gender":"gender","Blood Type":"blood_type",
            "Medical Condition":"medical_condition","Date of Admission":"date_of_admission","Doctor":"doctor","Hospital":"hospital","Insurance Provider":"insurance_provider",
            "Billing Amount":"billing_amount","Room Number":"room_number","Admission Type":"admission_type","Discharge Date":"discharge_date","Medication":"medication","Test Results":"test_results"})
    # Normaliser les noms, enlevement des civilités
    data['name'] = data['name'].str.title()
    data['name'] = data['name'].str.strip()
    data['name'] = data['name'].str.replace(r'\b(Mr\.|Dr\.|Mrs\.|Ms\.)\s*', '', regex=True)
    # Arrondi des montants et décompte des valeurs négatives
    data['billing_amount'] = data['billing_amount'].round(2)
    if data[data['billing_amount'] < 0].shape[0] > 0:
        print(f"ATTENTION:Nombre de valeurs négatives dans 'billing_amount' : {data[data['billing_amount'] < 0].shape[0]}")
    else:
        print("Aucune valeur négative dans 'billing_amount'")

    # Normaliser les dates
    data['date_of_admission'] = pd.to_datetime(data['date_of_admission'], errors="coerce")
    data['discharge_date'] = pd.to_datetime(data['discharge_date'], errors="coerce")
    # Modification de l'ordre des colonnes
    data = data[["patient_id","name","age","gender","blood_type","medical_condition","date_of_admission","doctor","hospital","insurance_provider",
                 "billing_amount","room_number","admission_type","discharge_date","medication","test_results"]]
    return data

if __name__ == "__main__":
    # Charger les variables d'environnement
    load_dotenv()
    input_path = "./data/healthcare_dataset.csv"
    output_path = "./data/cleaned_healthcare_dataset.csv"
    try:
        print(f"Original data shape: {pd.read_csv(input_path).shape}")
        # Nettoyer les données et les sauvegarder dans un nouveau fichier CSV
        cleaned_data = clean_data(input_path)
        cleaned_data.to_csv(output_path, index=False)
        print(f"Cleaned data shape: {pd.read_csv(output_path).shape}")
        print(f"Data cleaned and saved to {output_path}")
    except Exception as e:
        print(f"Error during data cleaning: {e}")
        raise e
# clean_data(input_path)

Original data shape: (55500, 15)
ATTENTION:Nombre de valeurs négatives dans 'billing_amount' : 106
Cleaned data shape: (54966, 16)
Data cleaned and saved to ./data/cleaned_healthcare_dataset.csv

In [10]:
cleaned_data.dtypes

patient_id                     int64
name                             str
age                            int64
gender                           str
blood_type                       str
medical_condition                str
date_of_admission     datetime64[us]
doctor                           str
hospital                         str
insurance_provider               str
billing_amount               float64
room_number                    int64
admission_type                   str
discharge_date        datetime64[us]
medication                       str
test_results                     str
dtype: object

In [11]:
cleaned_data

,patient_id,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328,Urgent,2024-02-02,Paracetamol,Normal
1,1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,205,Emergency,2022-10-07,Aspirin,Normal
3,3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.71,417,Elective,2020-09-15,Penicillin,Abnormal
55496,55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.80,316,Elective,2020-02-01,Aspirin,Normal
55497,55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.76,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.09,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.13,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [5]:
data = data.rename(columns={"patient_id":"patient_id","Name":"name","Age":"age","Gender":"gender","Blood Type":"blood_type",
            "Medical Condition":"medical_condition","Date of Admission":"date_of_admission","Doctor":"doctor","Hospital":"hospital","Insurance Provider":"insurance_provider",
            "Billing Amount":"billing_amount","Room Number":"room_number","Admission Type":"admission_type","Discharge Date":"discharge_date","Medication":"medication","Test Results":"test_results"})
data

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [6]:
cleaned_data

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,patient_id
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328,Urgent,2024-02-02,Paracetamol,Normal,0
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,1
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,205,Emergency,2022-10-07,Aspirin,Normal,2
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78,450,Elective,2020-12-18,Ibuprofen,Abnormal,3
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,458,Urgent,2022-10-09,Penicillin,Abnormal,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.71,417,Elective,2020-09-15,Penicillin,Abnormal,55495
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.80,316,Elective,2020-02-01,Aspirin,Normal,55496
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.76,347,Urgent,2020-08-10,Ibuprofen,Abnormal,55497
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.09,321,Elective,2019-05-31,Ibuprofen,Abnormal,55498
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.13,448,Urgent,2024-04-29,Ibuprofen,Abnormal,55499

In [17]:
data['date_of_admission'] = pd.to_datetime(data['date_of_admission'], unit='s')

In [18]:
data['date_of_admission']

0       2024-01-31
1       2019-08-20
2       2022-09-22
3       2020-11-18
4       2022-09-19
           ...
55495   2020-08-16
55496   2020-01-23
55497   2020-07-13
55498   2019-05-25
55499   2024-04-02
Name: date_of_admission, Length: 55500, dtype: datetime64[us]

In [14]:
data['name'] = data['name'].str.replace(r'^(Ms\.|Mr\.|Mrs\.|Dr\.)\s+', '', regex=True)

NameError: name 'data' is not defined

In [17]:
len(cleaned_data)

54966

In [18]:
import math


chunk_size = 10
num_chunks = math.ceil((len(cleaned_data) / chunk_size))

print(f"Number of chunks: {num_chunks}")

Number of chunks: 5497

In [19]:
print(mongodb_uri)

NameError: name 'mongodb_uri' is not defined